------------------------------
----- NOE classes defs -------
------------------------------

unitInfoDef = {
    [""] = "",
}

--- only list, each unit will have own N.O.E. stats
classDefLists = {
    ---- valuable classes ----
    {
	    ["class"]  = "valuable", 
	    ["name"]   = "metal",
		["static"] = true,
		["list"]   = {
		    "armmex",
			"armfmex",
			--"armuwmex",
			"armmoho",
			"armmmkr",
			"cormex",
			"corfmex",
			--"coruwmex",
			"cormoho",
			"cormmkr",
		},
	},
	{
	    ["class"]  = "valuable",
	    ["name"]   = "energy",
		["static"] = true,
		["list"]   = {
		    "armfus",
			"armmfus",
			"corfus",
			"cormfus",
		},
	},
	{
	    ["class"]  = "valuable",
	    ["name"]   = "builders",
		["static"] = false,
		["list"]   = {
		    "armfark",
			"armck",
			"armcv",
			--"armca",
			--"armacsub",
			"cornecro",
			"corack",
			"corcv",
			--"corca",
			--"coracsub",
		},
	},
	{
	    ["class"]  = "valuable",
	    ["name"]   = "expTowers",
		["static"] = true,
		["list"]   = {
		    "arm2veh",
			"arm2air",
			"arm2def",
			"arm2kbot",
			"armlvl2",
			"armnanotc",
			"cor2air",
			"cor2def",
			"cor2kbot",
			"cor2veh",
			"corlvl2",
			"corntow",
		},
	},
	{
	    ["class"]  = "valuable",
	    ["name"]   = "factories",
		["static"] = true,
		["list"]   = {
		    -- ARM --
		    "armaap",
			"armalab",
			"armap",
			"armavp",
			"armcsy",
			"armhklab",
			"armhp",
			"armlab",
			"armshltx",
			"armvp",
			"armplab",
			"armplat",			
		    -- CORE --						
	        "coraap",
			"coralab",
			"corap",
			"coravp",
			"corvp",
			"corcsy",
			"corgant",
			"corhp",
			"corlab",
			"corplat",
			"corslab",
			"corvalkfac",
			"corplab",
			"armfff",
		},
	},
    {
	    ["class"]  = "valuable",
	    ["name"]   = "defWeapons",
		["static"] = true,
		["list"]   = {
		    "armanni",
			"armlaunch",
			"armguard",
			"armamb",
			"canon3g",
			"armbrtha",
			"armvulc",
			"armbox",
			"armemp",
			"armsilo",
			"armtabi",
			"armamd",
			"armmllt",
			--- CORE ---
		    "cordoom",
			"corpun",
			"cortoast",
			"omega",
			"corint",
			"corbuzz",
			"corsupergun",
			"splinter",
			"cortron",
			"corsilo",
			"corflu",
			"corfmd",
            "corfury2",			
		},
	},
	{
	    ["class"]  = "valuable",
	    ["name"]   = "radarGround",
		["static"] = false,
		["list"]   = {
		    "armmark",
			"armseer",
			"armrad",
			"corvoyr",
			"corvrad",
			"corrad",
		},
	},
	{
	    ["class"]  = "valuable",
	    ["name"]   = "radarAir",
		["static"] = false,
		["list"] = {
			--"armhawk",
			--"armsehak",
			--"corawac",
			--"corhunt",
		},
	},
	{
	    ["class"]  = "valuable",
	    ["name"]   = "sonar",
		["static"] = true,
		["list"]   = {
			--"armsonar",
			--"corsonar",	
		},
	},
	{
	    ["class"]  = "valuable",
	    ["name"]   = "jammers",
		["static"] = false,
		["list"]   = {
			"armaser",
			"armjam",
			"corspec",
			"coreter",
		},
	},
	{
	    ["class"]  = "valuable",
	    ["name"]   = "dangerousGroundUnits",
		["static"] = false,
		["list"] = {
		    "armodd",
			"armpod",
			"armcom",
			"armcom2",
			"avtr",
			"armmanni",
			"armmerl",
			"armscab",
			--- CORE ---
			"corgala",
			"cortraq",
			"corkrog",
			"corcom",
			"cordemo",
			"corvroc",
			"corhorg",
		},
	},
	{
	    ["class"]  = "valuable",
	    ["name"]   = "lessDangerousGroundUnits",
		["static"] = false,
		["list"]   = {
		    "armbull",
			--- CORE ---
			"corsumo",
			"corcrabe",
			"correap",
			"corgol",
		},
	},
	{
	    ["class"]  = "valuable",
	    ["name"]   = "dangerousNavyUnits",
		["static"] = false,
		["list"]   = {
			"armthovr",
			"armmcrus",
			"armbcrus",
			"armewar",
			"armcarry",
			"aseadragon",
			"armtib",
			--- CORE ---
			"corthovr",
			"coraat",
			"corsub",
			"corhmcrus",
			"corcarry",
			"corewar",
			"corbcrus",
			"corblackhy",
		},
	},
	{
	    ["class"]  = "valuable",
	    ["name"]   = "dangerousAirUnits",
		["static"] = false,
		["list"]   = {
			"armpnix",
			"blade",
			"corbtrans",
			--- CORE ---
			"corhurc",
			"corerb",
			"corsbomb",
			"corvalk",
			"corvalkii",
			"corff",
		},
	},
	{
	    ["class"]  = "valuable",
	    ["name"]   = "strategic",
		["static"] = true,
		["list"]   = {
			"armamd",
			"armsilo",
			--- CORE ---
			"corfmd",
			"corsilo",
		},
	},
	---- leaders ----
	{
	    ["class"]  = "leaders",
	    ["name"]   = "commandCentre",
		["static"] = false,
		["list"]   = {
		    "armbase",
			"armcom",
			"armcom2",
			"corbase",
			"corcom",
			"corcom2",
		},
	},
	--- other classes ---
	{
	    ["class"]  = "mexes",
	    ["name"]   = "groundMexesOfArm",
		["side"]   = "arm",
		["static"] = true,
		["water"]  = false,
		["list"]   = {
		    "armmex",
			"armmoho",
		},
	},
		{
	    ["class"]  = "mexes",
	    ["name"]   = "groundMexesOfCore",
		["side"]   = "core",
		["static"] = true,
		["water"]  = false,
		["list"]   = {
			"cormex",
			"cormoho",
		},
	},
		{
	    ["class"]  = "mexes",
	    ["name"]   = "waterMexesOfArm",
		["side"]   = "arm",
		["static"] = true,
		["water"]  = true,
		["list"]   = {
			"armfmex",
			"armuwmex",
		},
	},
		{
	    ["class"]  = "mexes",
	    ["name"]   = "waterMexesOfCore",
		["side"]   = "core",
		["static"] = true,
		["water"]  = true,
		["list"]   = {
			"corfmex",
			"coruwmex",
		},
	},
}

    -- ["ahermes"] = false,
	-- ["ahkbc"] = false,
	-- ["arm2air"] = true,
	-- ["arm2def"] = true,
	-- ["arm2kbot"] = true,
	-- ["arm2veh"] = true,
	-- ["armaacrus"] = true,
	-- ["armaap"] = true,
	-- ["armacar"] = false,
	-- ["armack"] = false,
	-- ["armacsub"] = false,
	-- ["armah"] = false,
	-- ["armajam"] = false,
	-- ["armalab"] = true,
	-- ["armamb"] = false,
	-- ["armamd"] = false,
	-- ["armamph"] = false,
	-- ["armanac"] = false,
	-- ["armangel"] = false,
	-- ["armanni"] = true,
	-- ["armap"] = false,
	-- ["armarspd"] = false,
	-- ["armart"] = false,
	-- ["armaser"] = false,
	-- ["armasp"] = false,
	-- ["armasubh"] = false,
	-- ["armatlas"] = false,
	-- ["armavp"] = false,
	-- ["armawac"] = false,
	-- ["armbase"] = true,
	-- ["armbcom"] = false,
	-- ["armbcrus"] = false,
	-- ["armbeac"] = false,
	-- ["armbox"] = false,
	-- ["armbrawl"] = false,
	-- ["armbrtha"] = true,
	-- ["armbrtha_dgun"] = false,
	-- ["armbull"] = false,
	-- ["armca"] = false,
	-- ["armcarry"] = false,
	-- ["armch"] = false,
	-- ["armck"] = false,
	-- ["armcom"] = true,
	-- ["armcom2"] = true,
	-- ["armcrach"] = false,
	-- ["armcroc"] = false,
	-- ["armcrus"] = false,
	-- ["armcsy"] = true,
	-- ["armcv"] = false,
	-- ["armdev1"] = false,
	-- ["armdrag"] = false,
	-- ["armdragf"] = false,
	-- ["armdrake"] = false,
	-- ["armdrone"] = false,
	-- ["armemp"] = false,
	-- ["armestor"] = false,
	-- ["armewar"] = false,
	-- ["armexcal"] = false,
	-- ["armexcal2"] = false,
	-- ["armfark"] = false,
	-- ["armfast"] = false,
	-- ["armfav"] = false,
	-- ["armfdrag"] = false,
	-- ["armfff"] = false,
	-- ["armfhlt"] = false,
	-- ["armfido"] = false,
	-- ["armfig"] = false,
	-- ["armflak"] = false,
	-- ["armflash"] = false,
	-- ["armflea"] = false,
	-- ["armfmex"] = false,
	-- ["armfmkr"] = false,
	-- ["armfort"] = false,
	-- ["armfus"] = false,
	-- ["armgeo"] = false,
	-- ["armguard"] = false,
	-- ["armham"] = false,
	-- ["armhawk"] = false,
	-- ["armhell"] = false,
	-- ["armhklab"] = false,
	-- ["armhlt"] = false,
	-- ["armhmcrus"] = false,
	-- ["armhover3g"] = false,
	-- ["armhp"] = false,
	-- ["armjam"] = false,
	-- ["armjeth"] = false,
	-- ["armlab"] = false,
	-- ["armlance"] = false,
	-- ["armlatnk"] = false,
	-- ["armlaunch"] = false,
	-- ["armllt"] = false,
	-- ["armlvl2"] = false,
	-- ["armmakr"] = false,
	-- ["armmanni"] = false,
	-- ["armmark"] = false,
	-- ["armmart"] = false,
	-- ["armmav"] = false,
	-- ["armmcrus"] = false,
	-- ["armmerl"] = false,
	-- ["armmex"] = false,
	-- ["armmfus"] = false,
	-- ["armmine3"] = false,
	-- ["armmine4"] = false,
	-- ["armmine5"] = false,
	-- ["armmine6"] = false,
	-- ["armmllt"] = false,
	-- ["armmllt2"] = false,
	-- ["armmmkr"] = false,
	-- ["armmoho"] = false,
	-- ["armmstor"] = false,
	-- ["armnanotc"] = false,
	-- ["armodd"] = false,
	-- ["armpeep"] = false,
	-- ["armplab"] = false,
	-- ["armplat"] = false,
	-- ["armpnix"] = false,
	-- ["armpod"] = false,
	-- ["armpt"] = false,
	-- ["armpw"] = false,
	-- ["armrad"] = false,
	-- ["armraz"] = false,
	-- ["armrb"] = false,
	-- ["armrl"] = false,
	-- ["armrock"] = false,
	-- ["armsalvo"] = false,
	-- ["armsam"] = false,
	-- ["armscab"] = false,
	-- ["armseap"] = false,
	-- ["armseer"] = false,
	-- ["armsehak"] = false,
	-- ["armserp"] = false,
	-- ["armsfig"] = false,
	-- ["armsh"] = false,
	-- ["armshltx"] = false,
	-- ["armsilo"] = false,
	-- ["armsl"] = false,
	-- ["armsnipe"] = false,
	-- ["armsolar"] = false,
	-- ["armsonar"] = false,
	-- ["armspid"] = false,
	-- ["armspy"] = false,
	-- ["armstump"] = false,
	-- ["armtabi"] = false,
	-- ["armtflak"] = false,
	-- ["armthovr"] = false,
	-- ["armthund"] = false,
	-- ["armtib"] = false,
	-- ["armtide"] = false,
	-- ["armtl"] = false,
	-- ["armtoad"] = false,
	-- ["armtruck"] = false,
	-- ["armuwasp"] = false,
	-- ["armuwmex"] = false,
	-- ["armvader"] = false,
	-- ["armvp"] = false,
	-- ["armvulc"] = false,
	-- ["armvulc_pw"] = false,
	-- ["armwar"] = false,
	-- ["armwin"] = false,
	-- ["armwing"] = false,
	-- ["armyork"] = false,
	-- ["armzeus"] = false,
	-- ["aseadragon"] = false,
	-- ["avtr"] = false,
	-- ["blade"] = false,
	-- ["bladewing"] = false,
	-- ["bug1"] = false,
	-- ["bug2"] = false,
	-- ["bug3"] = false,
	-- ["bug4"] = false,
	-- ["bug5"] = false,
	-- ["canon3g"] = false,
	-- ["chickend"] = false,
	-- ["cmercdrag"] = false,
	-- ["cor2air"] = false,
	-- ["cor2def"] = false,
	-- ["cor2kbot"] = false,
	-- ["cor2veh"] = false,
	-- ["coraacrus"] = false,
	-- ["coraap"] = false,
	-- ["coraat"] = false,
	-- ["corack"] = false,
	-- ["coracsub"] = false,
	-- ["corah"] = false,
	-- ["corajam"] = false,
	-- ["corak"] = false,
	-- ["coralab"] = false,
	-- ["coramph"] = false,
	-- ["corap"] = false,
	-- ["corape"] = false,
	-- ["corasp"] = false,
	-- ["corasubh"] = false,
	-- ["coravp"] = false,
	-- ["corawac"] = false,
	-- ["corbase"] = false,
	-- ["corbcrus"] = false,
	-- ["corblackhy"] = false,
	-- ["corbrik"] = false,
	-- ["corbtrans"] = false,
	-- ["corbuzz"] = false,
	-- ["corbuzz_ak"] = false,
	-- ["corca"] = false,
	-- ["corcan"] = false,
	-- ["corcarry"] = false,
	-- ["corch"] = false,
	-- ["corck"] = false,
	-- ["corcom"] = false,
	-- ["corcom2"] = false,
	-- ["corcrabe"] = false,
	-- ["corcrash"] = false,
	-- ["corcrus"] = false,
	-- ["corcsy"] = false,
	-- ["corcv"] = false,
	-- ["cordcarry"] = false,
	-- ["cordemo"] = false,
	-- ["cordest"] = false,
	-- ["cordoom"] = false,
	-- ["cordrag"] = false,
	-- ["corerb"] = false,
	-- ["corestor"] = false,
	-- ["coreter"] = false,
	-- ["corevashp"] = false,
	-- ["corewar"] = false,
	-- ["corfast"] = false,
	-- ["corfatnk"] = false,
	-- ["corfav"] = false,
	-- ["corff"] = false,
	-- ["corfhlt"] = false,
	-- ["corfink"] = false,
	-- ["corflak"] = false,
	-- ["corflu"] = false,
	-- ["corfmd"] = false,
	-- ["corfmex"] = false,
	-- ["corfmkr"] = false,
	-- ["corfort"] = false,
	-- ["corfury"] = false,
	-- ["corfury2"] = false,
	-- ["corfus"] = false,
	-- ["corgala"] = false,
	-- ["corgamma"] = false,
	-- ["corgamma2"] = false,
	-- ["corgant"] = false,
	-- ["corgate"] = false,
	-- ["corgator"] = false,
	-- ["corgeo"] = false,
	-- ["corgol"] = false,
	-- ["corgryp"] = false,
	-- ["corhktank"] = false,
	-- ["corhlt"] = false,
	-- ["corhmcrus"] = false,
	-- ["corhorg"] = false,
	-- ["corhp"] = false,
	-- ["corhrk"] = false,
	-- ["corhunt"] = false,
	-- ["corhurc"] = false,
	-- ["corint"] = false,
	-- ["corint_dgun"] = false,
	-- ["corkrog"] = false,
	-- ["corlab"] = false,
	-- ["corlevlr"] = false,
	-- ["corllt"] = false,
	-- ["corlvl2"] = false,
	-- ["cormabm"] = false,
	-- ["cormak"] = false,
	-- ["cormakr"] = false,
	-- ["cormart"] = false,
	-- ["cormblade"] = false,
	-- ["cormex"] = false,
	-- ["cormfus"] = false,
	-- ["cormh"] = false,
	-- ["cormine1"] = false,
	-- ["cormine2"] = false,
	-- ["cormine3"] = false,
	-- ["cormine6"] = false,
	-- ["cormist"] = false,
	-- ["cormmkr"] = false,
	-- ["cormoho"] = false,
	-- ["cormonsta"] = false,
	-- ["cormonstab"] = false,
	-- ["cormonstaq"] = false,
	-- ["cormort"] = false,
	-- ["cormstor"] = false,
	-- ["cornecro"] = false,
	-- ["corntow"] = false,
	-- ["corplab"] = false,
	-- ["corplas"] = false,
	-- ["corplat"] = false,
	-- ["corpt"] = false,
	-- ["corpun"] = false,
	-- ["corpyro"] = false,
	-- ["corrad"] = false,
	-- ["corraid"] = false,
	-- ["correap"] = false,
	-- ["corrl"] = false,
	-- ["corroach"] = false,
	-- ["corsbomb"] = false,
	-- ["corseal"] = false,
	-- ["corseap"] = false,
	-- ["corsent"] = false,
	-- ["corsfig"] = false,
	-- ["corsh"] = false,
	-- ["corshad"] = false,
	-- ["corsilo"] = false,
	-- ["corslab"] = false,
	-- ["corsnap"] = false,
	-- ["corsolar"] = false,
	-- ["corsonar"] = false,
	-- ["corspec"] = false,
	-- ["corspy"] = false,
	-- ["corstorm"] = false,
	-- ["corsub"] = false,
	-- ["corsumo"] = false,
	-- ["corsupergun"] = false,
	-- ["corsupergun_pyro"] = false,
	-- ["cortflak"] = false,
	-- ["corthovr"] = false,
	-- ["corthud"] = false,
	-- ["cortide"] = false,
	-- ["cortitan"] = false,
	-- ["cortl"] = false,
	-- ["cortoast"] = false,
	-- ["cortraq"] = false,
	-- ["cortron"] = false,
	-- ["cortruck"] = false,
	-- ["coruwasp"] = false,
	-- ["coruwmex"] = false,
	-- ["corvalk"] = false,
	-- ["corvalkfac"] = false,
	-- ["corvalkii"] = false,
	-- ["corvamp"] = false,
	-- ["corveng"] = false,
	-- ["corvipe"] = false,
	-- ["corvoyr"] = false,
	-- ["corvp"] = false,
	-- ["corvrad"] = false,
	-- ["corvroc"] = false,
	-- ["corwalks"] = false,
	-- ["corwin"] = false,
	-- ["cougar"] = false,
	-- ["darkswarmunit"] = false,
	-- ["dca"] = false,
	-- ["emperunit"] = false,
	-- ["grayhound"] = false,
	-- ["madcat"] = false,
	-- ["mercury"] = false,
	-- ["omega"] = false,
	-- ["pit_viper"] = false,
	-- ["raptoriv"] = false,
	-- ["repdrone"] = false,
	-- ["repmum"] = false,
	-- ["roost"] = false,
	-- ["scramerunit"] = false,
	-- ["shika"] = false,
	-- ["spawner_asteroid"] = false,
	-- ["spawner_kdart"] = false,
	-- ["spawner_rockstorm"] = false,
	-- ["spit3g"] = false,
	-- ["splinter"] = false,
	-- ["sprint"] = false,
	-- ["wormy"] = false,